### ISSUE TITLE
Getting the delete part to work

### ISSUE THREAD

**Issue by newterminator** [Joseph-N/dropezonejs-rails#1]
Hey Joseph,
I wanted to mention first of all that your implementation for the ajax multiple file upload with dropzone for rails 4 was amazing and it just worked perfectly. I spent days searching for a solution like yours. 
I wanted to ask you that in your blog and in the sample app, the delete part or "remove file" was not implemented, so if you could kindly update the code to reflect that as well, it would be great.

**Comment by Joseph-N** [comment]
Hi newterminator,
Thank you so much for reading my post and finding it helpful. I am planning on updating the tutorial to include this feature as it turns out to be one of the most requested one. Could you please post this in the comments section of the tutorial? I would really appreciate it since there its more open, and we will help more audience.

Thanks
